import Foundation
import CryptoKit

class LicenseManager: ObservableObject {
    @Published var isValid: Bool = false
    @Published var expiresAt: Date? = nil
    @Published var statusMessage: String = "No license"

    static let shared = LicenseManager()
    private let storageKey = "xrd_license_key"
    private let secret = "XRD-AGAR-SECRET-2024-ONLY-HE-KNOWS"

    init() {
        if let saved = UserDefaults.standard.string(forKey: storageKey) {
            _ = validate(key: saved)
        }
    }

    @discardableResult
    func validate(key: String) -> Bool {
        guard let decoded = decodeKey(key) else {
            isValid = false
            statusMessage = "Invalid key format"
            return false
        }

        if decoded.expiry < Date() {
            isValid = false
            statusMessage = "Key expired"
            return false
        }

        if !verifySignature(payload: decoded.payload, signature: decoded.signature) {
            isValid = false
            statusMessage = "Invalid key signature"
            return false
        }

        isValid = true
        expiresAt = decoded.expiry
        UserDefaults.standard.set(key, forKey: storageKey)

        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        statusMessage = "Valid until \(formatter.string(from: decoded.expiry))"
        return true
    }

    func revoke() {
        isValid = false
        expiresAt = nil
        statusMessage = "No license"
        UserDefaults.standard.removeObject(forKey: storageKey)
    }

    // Key format: XRD-{base64(timestamp|duration_hours)}-{hmac_signature_hex_prefix}
    // Generated by the key generator (Discord bot or HTML tool)

    struct DecodedKey {
        let payload: String
        let signature: String
        let expiry: Date
    }

    private func decodeKey(_ key: String) -> DecodedKey? {
        let parts = key.split(separator: "-")
        guard parts.count >= 3, parts[0] == "XRD" else { return nil }

        let payloadB64 = String(parts[1])
        let sig = String(parts[2])

        guard let payloadData = Data(base64Encoded: payloadB64),
              let payloadStr = String(data: payloadData, encoding: .utf8) else { return nil }

        let payloadParts = payloadStr.split(separator: "|")
        guard payloadParts.count == 2,
              let timestamp = TimeInterval(payloadParts[0]),
              let durationHours = Int(payloadParts[1]) else { return nil }

        let createdAt = Date(timeIntervalSince1970: timestamp)
        let expiry = createdAt.addingTimeInterval(TimeInterval(durationHours) * 3600)

        return DecodedKey(payload: payloadB64, signature: sig, expiry: expiry)
    }

    private func verifySignature(payload: String, signature: String) -> Bool {
        let key = SymmetricKey(data: Data(secret.utf8))
        let mac = HMAC<SHA256>.authenticationCode(for: Data(payload.utf8), using: key)
        let fullHex = mac.map { String(format: "%02x", $0) }.joined()
        return fullHex.hasPrefix(signature)
    }

    // MARK: - Key Generation (for the generator tools only)

    static func generateKey(durationHours: Int, secret: String = "XRD-AGAR-SECRET-2024-ONLY-HE-KNOWS") -> String {
        let timestamp = Date().timeIntervalSince1970
        let payload = "\(Int(timestamp))|\(durationHours)"
        let payloadB64 = Data(payload.utf8).base64EncodedString()

        let key = SymmetricKey(data: Data(secret.utf8))
        let mac = HMAC<SHA256>.authenticationCode(for: Data(payloadB64.utf8), using: key)
        let sig = mac.map { String(format: "%02x", $0) }.joined().prefix(16)

        return "XRD-\(payloadB64)-\(sig)"
    }
}
